#!/usr/bin/python3
'''
Main source file for poeng game
'''

import pygame
from pygame.locals import *

class Game:
    def __init__(self):
        self._running = True
        self._display_surf = None
        self.size = self.weight, self.height = 1280, 960

    def on_key_down(self, event):
        print("You pressed a key")
    def on_init(self):
        pygame.init()
        self._display_surf = pygame.display.set_mode(self.size, pygame.HWSURFACE | pygame.DOUBLEBUF)
        self._running = True
        self.cat = Cat()

    def on_event(self, event):
        if event.type == pygame.QUIT:
            self._running = False
        elif event.type == KEYDOWN:
            self.on_key_down(event)

    def on_loop(self):
        pass

    def on_render(self):
        self._display_surf.blit(self.cat.image, self.cat.position)
        pygame.display.flip()

    def on_cleanup(self):
        pygame.quit()

    def on_execute(self):
        if self.on_init() == False:
            self._running = False

        while( self._running ):
            for event in pygame.event.get():
                self.on_event(event)
                self.on_loop()
                self.on_render()
        self.on_cleanup()

# This is a cat object
class Cat:
    def __init__(self):
        self.image = pygame.image.load("cat.png").convert()
        self.position = (0,0)


if __name__ == "__main__" :
    game = Game()
    game.on_execute()
