#!/usr/bin/python3
'''
Main source file for poeng game
'''

import pygame
from ball import Ball
from paddle import Paddle
from pygame.locals import *

class Game:
    def __init__(self):
        self._running = True
        self.screen = None
        self.size = self.weight, self.height = 1280, 960
        self.clock = pygame.time.Clock()
        self.bgColor = (210,210,210)


    def on_key_down(self, event):
        print("poop")

    def on_init(self):
        pygame.init()
        pygame.key.set_repeat(1,1)
        pygame.mixer.music.load('sounds/bgm.mp3')
        pygame.mixer.music.play(-1)
        self.screen = pygame.display.set_mode(self.size, pygame.HWSURFACE | pygame.DOUBLEBUF)
        self._running = True
        self.objectList = pygame.sprite.Group()
        self.ball = Ball(500,500, self.size)
        self.paddle = Paddle(0,0, self.size)
        self.objectList.add(self.paddle)
        self.objectList.add(self.ball)

    def on_event(self, event):
        if event.type == pygame.QUIT:
            self._running = False
        elif event.type == KEYDOWN:
            if event.key == pygame.K_w:
                self.paddle.move('up')

            if event.key == pygame.K_s:
                self.paddle.move('down')

    def on_loop(self):
        if pygame.sprite.collide_rect(self.ball, self.paddle):
            print("Collide")
            self.ball.sendHit()
    def on_render(self):
        self.drawBackgound()
        self.objectList.draw(self.screen)
        self.objectList.update()
        self.clock.tick(100)
        pygame.display.flip()

    def on_cleanup(self):
        pygame.quit()

    def on_execute(self):
        if self.on_init() == False:
            self._running = False

        #----- Main game loop ------
        while( self._running ):
            for event in pygame.event.get():
                self.on_event(event)
            self.on_loop()
            self.on_render()
        self.on_cleanup()

    def drawBackgound(self):
        self.screen.fill(self.bgColor)


if __name__ == "__main__" :
    game = Game()
    game.on_execute()
