#!/usr/bin/python3
'''
Main source file for poeng game
'''

import pygame
from ball import Ball
from pygame.locals import *

class Game:
    def __init__(self):
        self._running = True
        self.screen = None
        self.size = self.weight, self.height = 1280, 960

    def on_key_down(self, event):
        self.screen.fill((255,0,255))
        self.ball.moveDown()
        self.ball.scale()
    def on_init(self):
        pygame.init()
        self.screen = pygame.display.set_mode(self.size, pygame.HWSURFACE | pygame.DOUBLEBUF)
        self._running = True
        self.ball = Ball()

    def on_event(self, event):
        if event.type == pygame.QUIT:
            self._running = False
        elif event.type == KEYDOWN:
            self.on_key_down(event)

    def on_loop(self):
        pass

    def on_render(self):
        self.screen.blit(self.ball.image, self.ball.position)
        pygame.display.flip()

    def on_cleanup(self):
        pygame.quit()

    def on_execute(self):
        if self.on_init() == False:
            self._running = False

        while( self._running ):
            for event in pygame.event.get():
                self.on_event(event)
                self.on_loop()
                self.on_render()
        self.on_cleanup()



if __name__ == "__main__" :
    game = Game()
    game.on_execute()
